package com.example.recipes.model

import java.io.Serializable

data class RecipeModel(
    val approved_at: Int,
    val aspect_ratio: String,
    val beauty_url: Any,
    val brand: Any,
    val brand_id: Any,
    val buzz_id: Any,
    val canonical_id: String,
    val compilations: List<Compilation>,
    val cook_time_minutes: Any,
    val country: String,
    val created_at: Int,
    val credits: List<Credit>,
    val description: String,
    val draft_status: String,
    val facebook_posts: List<Any>,
    val id: Int,
    val inspired_by_url: Any,
    val instructions: List<Instruction>,
    val is_one_top: Boolean,
    val is_shoppable: Boolean,
    val keywords: Any,
    val language: String,
    val name: String,
    val num_servings: Int,
    val nutrition: Nutrition,
    val nutrition_visibility: String,
    val original_video_url: Any,
    val prep_time_minutes: Any,
    val promotion: String,
    val recipes: List<RecipeX>,
    val renditions: List<RenditionX>,
    val sections: List<SectionX>,
    val seo_title: String,
    val servings_noun_plural: String,
    val servings_noun_singular: String,
    val show: ShowXXX,
    val show_id: Int,
    val slug: String,
    val tags: List<TagX>,
    val thumbnail_alt_text: String,
    val thumbnail_url: String,
    val tips_and_ratings_enabled: Boolean,
    val topics: List<TopicX>,
    val total_time_minutes: Any,
    val total_time_tier: Any,
    val updated_at: Int,
    val user_ratings: UserRatingsX,
    val video_ad_content: Any,
    val video_id: Int,
    val video_url: String,
    val yields: String
): Serializable